---
- name: Configure Server
  hosts: db-server
  become: yes

  tasks:
  - name: Install Docker
    import_role:
      name: docker

  - name: Install Postgres
    import_role:
      name: k8-postgres