---
- name: Create a VM folder
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../{{ vm_name }}"
    state: directory
- name: Get TF files
  fetch:
    src: /home/TF_FILES/
    dest: "{{ playbook_dir }}/../{{ vm_name }}/"
  delegate_to: '{{ vm_ip.stdout }}'
- name: Terraform destroy
  command:
    chdir: "{{ playbook_dir }}/../{{ vm_name }}"
    cmd: "terraform destroy -auto-approve"
  environment:
    TF_VAR_proxmox_api_token_id: "{{ lookup('env', 'TF_VAR_proxmox_api_token_id') }}"
    TF_VAR_proxmox_api_token_secret: "{{ lookup('env', 'TF_VAR_proxmox_api_token_secret') }}"
  register: terraform_destroy

- name: Terraform apply output
  debug:
    msg: "{{ terraform_destroy }}"
