---
- name: Terraform init, plan and apply
  become: yes

  environment:
    TF_VAR_proxmox_api_token_id: ''
    TF_VAR_proxmox_api_token_secret: ''

  tasks:
  - name: Create a VM folder
    ansible.builtin.file:
      path: "{{ playbook_dir }}/../{{ vm_name }}"
      state: directory
  - name: Create TF vars file
    template:
      src: templates/create_vm.tf.j2
      dest: "{{ playbook_dir }}/../{{ vm_name }}/create_vm.tf"

  - name: Copy over TF files
    copy:
      src: "{{ playbook_dir }}/../{{ item }}"
      dest: "{{ playbook_dir }}/../{{ vm_name }}/{{ item }}"
    loop:
      - ../provider.tf

  - name: Terraform init
    command:
      chdir: "{{ playbook_dir }}/../{{ vm_name }}"
      cmd: "terraform init"
    register: terraform_init

  - name: Terraform init output
    debug:
      msg: "{{ terraform_init }}"

  - name: Terraform plan
    command:
      chdir: "{{ playbook_dir }}/../{{ vm_name }}"
      cmd: "terraform plan"
    register: terraform_plan

  - name: Terraform plan output
    debug:
      msg: "{{ terraform_plan }}"

  - name: Terraform apply
    command:
      chdir: "{{ playbook_dir }}/../{{ vm_name }}"
      cmd: "terraform apply -auto-approve"
    register: terraform_apply

  - name: Terraform init output
    debug:
      msg: "{{ terraform_apply }}"
